language: node_js
node_js:
  - "0.12"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/802d71d2c548c03a0d59
    on_success: always  # options: [always|never|change]
    on_failure: always  # options: [always|never|change]
    on_start: false     # default: false